name: Cross-platform Release

on:
  push:
    branches:
      - "*" 

jobs:
  build:
    name: Build - ${{ matrix.os-name }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        os-name: [Linux-x86_64, Windows-x86_64, macOS-arm64]
        runs-on: [ubuntu-24.04, windows-latest, macos-latest]
        target: [x86_64-unknown-linux-musl, x86_64-pc-windows-msvc, aarch64-apple-darwin]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.target }}
          args: "--locked --release"
          strip: true
