name: Cross-platform Release

on:
  push:
    branches:
      - "*" 

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: FreeBSD-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-freebsd

          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl

          - os-name: Linux-aarch64
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-musl

          - os-name: Linux-riscv64
            runs-on: ubuntu-24.04
            target: riscv64gc-unknown-linux-gnu

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin

          # more targets here ...

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install OpenSSL (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev
      - name: Install OpenSSL (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install openssl
      - name: Install OpenSSL (FreeBSD)
        if: runner.os == 'FreeBSD'
        run: |
          sudo pkg update
          sudo pkg install -y openssl
      # For Windows, OpenSSL is often handled by vcpkg or pre-installed.
      # If you encounter issues, you might need to add a specific step here.
      - name: Install OpenSSL (Windows)
        if: runner.os == 'Windows'
        run: |
          # Install vcpkg if not already present
          if (-not (Test-Path "$env:VCPKG_ROOT")) {
            git clone https://github.com/microsoft/vcpkg.git $env:VCPKG_ROOT
            & "$env:VCPKG_ROOT\bootstrap-vcpkg.bat"
          }
          # Install openssl
          & "$env:VCPKG_ROOT\vcpkg.exe" install openssl:x64-windows-static-md
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: ubi
          target: ${{ matrix.platform.target }}
