name: Cross-platform Release

on:
  push:
    branches:
      - "*" 

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl

          - os-name: Linux-aarch64
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-musl

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release --no-default-features --features rustls/ring,bindgen"
          strip: true
        env:
          AWS_LC_SYS_CMAKE_BUILDER: 1
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: ubi
          target: ${{ matrix.platform.target }}

  freebsd_release:
    name: Release - FreeBSD-x86_64
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: pkg install -y rust
          run: |
            cd "$GITHUB_WORKSPACE"
            cargo build --locked --release --target=x86_64-unknown-freebsd --no-default-features --features rustls/ring,bindgen
            strip target/x86_64-unknown-freebsd/release/ubi
            ls -l target/x86_64-unknown-freebsd/release/ubi
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubi-x86_64-unknown-freebsd
          path: target/x86_64-unknown-freebsd/release/ubi
