name: Release
# E

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    uses: axodotdev/cargo-dist/.github/workflows/release.yml@main
    with:
      tag: ${{ github.ref_name }}

